<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-BOVJ3NS" name="test2" tests="2" failures="1" timestamp="25 Jun 2020 15:31:09 GMT" time="79.67" errors="0">
  <testcase name="loginValidCredentials" time="8.59" classname="Scripts.LoginSite"/>
  <testcase name="loginInvalidCredentials" time="6.116" classname="Scripts.LoginSite">
    <failure type="java.lang.AssertionError" message="expected [Welcome to your account. Here you can manage all of your personal information and orders.] but found [Authentication failed.]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to your account. Here you can manage all of your personal information and orders.] but found [Authentication failed.]
	at Scripts.LoginSite.loginInvalidCredentials(LoginSite.java:103)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginInvalidCredentials -->
</testsuite> <!-- test2 -->
